# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: jacin@elrocin.es
description: > # this means to ignore newlines until "baseurl:"
  Jacinto Arias personal website. Comprehensive publication list,
  projects and research interests on Data Science, Data Mining and Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jacintoArias

# Build settings
markdown: kramdown
